// <auto-generated />
using Amy_Cherrez_Examen1P.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Amy_Cherrez_Examen1P.Migrations
{
    [DbContext(typeof(Amy_Cherrez_Examen1PContext))]
    [Migration("20231025130741_Inicio")]
    partial class Inicio
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Amy_Cherrez_Examen1P.Models.AmyCherrez_TablaFactura", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("AmDescription_Producto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AmPagoEfectivo")
                        .HasColumnType("bit");

                    b.Property<decimal>("AmPrecio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AmProducto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("AmyCherrez_TablaFactura");
                });
#pragma warning restore 612, 618
        }
    }
}
